= Wisdom OAuth 2.0 Protection Plugin
:toc:

//
// Copyright 2015 ForgeRock AS.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

== OAuth 2.0 Protection Plugin for Wisdom Framework

image:https://travis-ci.org/sauthieg/wisdom-oauth2-protection.svg["Build Status", link="https://travis-ci.org/sauthieg/wisdom-oauth2-protection"]

Wisdom Framework extension that protects routes against un-authorized access using the https://tools.ietf.org/html/rfc6749[OAuth 2.0 Framework].

 * Version: 1.0
 * License: Apache Software License 2.0
 * Authors: Guillaume Sauthier

== Usage

Add this dependency to your wisdom application:

[source, xml]
----
<dependency>
    <groupId>com.forgerock.wisdom.oauth2</groupId>
    <artifactId>wisdom-oauth2-protection</artifactId>
    <version>${oauth2-protection.version}</version>
</dependency>
----

Then you may add the +@Scopes+ annotation on your routes if you want to protect the decorated route:

[source, java]
----
@Scopes("http://wisdom.example.com/#write")
@Route(method = GET, uri = "/protected")
public Result underProtection() {
    // Do your usual logic here
    return ok();
}
----

If you add more scopes values in the +@Scopes+ annotation, all of the declared scopes will be required to access the action.
If one is missing, the request will be rejected.

=== Configuration

Your application configuration file needs to include the a config element.
In here you declare against which OAuth 2.0 provider you want to verify the extracted token.

[source]
----
oauth2-protection {
  // Declaration of the introspection service to use
  introspection-service {
    type = fake // <1>
    // Other properties can be passed here to configure the service instance
  }
}
----
<1> Mandatory property

=== Pre-defined TokenIntrospectionService types

This extension comes with a number of pre-defined +TokenIntrospectionService+ components.

Theses can be declared for use in the application configuration file (as described in the <<Configuration>> section)

==== Google

Link against https://developers.google.com/identity/protocols/OAuth2UserAgent#tokeninfo-validation[Google OAuth 2.0] endpoints.

There is no configuration properties available.

[source]
----
oauth2-protection {
  introspection-service {
    type = google
  }
}
----

==== ForgeRock OpenAM

Link against http://openam.forgerock.org/doc/bootstrap/admin-guide/index.html#chap-oauth2[ForgeRock OpenAM OAuth 2.0] endpoints.

[source]
----
oauth2-protection {
  introspection-service {
    type = openam
    baseUrl = http://openam.example.com/openam // <1>
    realm = /customers // <2>
  }
}
----
<1> Required
<2> Optional (defaults to top level realm +/+)

==== Standard

Link against https://tools.ietf.org/html/draft-ietf-oauth-introspection[OAuth 2.0 Introspection Endpoint] providers.

[source]
----
oauth2-protection {
  introspection-service {
    type = standard
    baseUrl = http://openam.example.com/openam/oauth2/introspection // <1>
    bearerToken = f9063e26-3a29-41ec-86de-1d0d68aa85e9 // <2>
  }
}
----
<1> Required, full URL of the introspection REST endpoint
<2> Optional, needed if the endpoint is OAuth 2.0 protected

== Disclaimer

This plugin is not supported by ForgeRock AS.
